package com.finguard.service;
import com.finguard.entity.*; import com.finguard.repository.*; import com.finguard.risk.RiskEvaluationService; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.*;
@Service public class TransactionService { private final AccountRepository accounts; private final TransactionRepository transactions; private final RiskEvaluationService risk; private final IdempotencyRepository idempotency; private final AuditLogRepository auditLogs; public TransactionService(AccountRepository a,TransactionRepository t,RiskEvaluationService r,IdempotencyRepository i,AuditLogRepository l){accounts=a;transactions=t;risk=r;idempotency=i;auditLogs=l;}
@Transactional public Transaction deposit(UUID userId,BigDecimal amount){validateAmount(amount); Account account=lockUserAccount(userId); Transaction transaction=saveEvaluated(account.getUser(),account,null,TransactionType.DEPOSIT,amount); if(transaction.getStatus()==TransactionStatus.APPROVED) account.setBalance(account.getBalance().add(amount)); return transaction;}
@Transactional public Transaction withdraw(UUID userId,BigDecimal amount){validateAmount(amount); Account account=lockUserAccount(userId); if(account.getBalance().compareTo(amount)<0)throw new IllegalArgumentException("Insufficient account balance"); Transaction transaction=saveEvaluated(account.getUser(),account,null,TransactionType.WITHDRAWAL,amount); if(transaction.getStatus()==TransactionStatus.APPROVED) account.setBalance(account.getBalance().subtract(amount)); return transaction;}
@Transactional public Transaction transfer(UUID userId,String destinationNumber,BigDecimal amount,String key){validateAmount(amount); if(key==null||key.isBlank())throw new IllegalArgumentException("Idempotency-Key is required"); Optional<IdempotencyRecord> existing=idempotency.findByIdempotencyKeyAndUserId(key,userId); if(existing.isPresent())return existing.get().getTransaction(); Account source=accounts.findByUserId(userId).orElseThrow(()->new IllegalArgumentException("Account not found")); Account destination=accounts.findByAccountNumber(destinationNumber).orElseThrow(()->new IllegalArgumentException("Destination account not found")); if(source.getId().equals(destination.getId()))throw new IllegalArgumentException("Cannot transfer to the same account"); Account first=source.getId().toString().compareTo(destination.getId().toString())<0?source:destination; Account second=first==source?destination:source; Account lockedFirst=accounts.findByIdForUpdate(first.getId()).orElseThrow(); Account lockedSecond=accounts.findByIdForUpdate(second.getId()).orElseThrow(); source=source.getId().equals(lockedFirst.getId())?lockedFirst:lockedSecond; destination=destination.getId().equals(lockedFirst.getId())?lockedFirst:lockedSecond; if(source.getBalance().compareTo(amount)<0)throw new IllegalArgumentException("Insufficient account balance"); Transaction transaction=saveEvaluated(source.getUser(),source,destination,TransactionType.TRANSFER,amount); if(transaction.getStatus()==TransactionStatus.APPROVED){source.setBalance(source.getBalance().subtract(amount)); destination.setBalance(destination.getBalance().add(amount));} IdempotencyRecord record=new IdempotencyRecord(); record.setIdempotencyKey(key); record.setUser(source.getUser()); record.setTransaction(transaction); idempotency.save(record); return transaction;}
private Account lockUserAccount(UUID userId){Account account=accounts.findByUserId(userId).orElseThrow(()->new IllegalArgumentException("Account not found")); return accounts.findByIdForUpdate(account.getId()).orElseThrow(()->new IllegalArgumentException("Account not found"));}
private Transaction saveEvaluated(User user,Account source,Account destination,TransactionType type,BigDecimal amount){Transaction transaction=new Transaction();transaction.setUser(user);transaction.setSourceAccount(source);transaction.setDestinationAccount(destination);transaction.setType(type);transaction.setAmount(amount);transaction.setStatus(TransactionStatus.PENDING);transaction.setTransactionReference("FG-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());transaction=transactions.save(transaction);RiskEvaluation evaluation=risk.evaluate(transaction);transaction.setStatus(evaluation.getDecision()==RiskDecision.APPROVED?TransactionStatus.APPROVED:evaluation.getDecision()==RiskDecision.REVIEW?TransactionStatus.REVIEW:TransactionStatus.BLOCKED);transaction=transactions.save(transaction);AuditLog log=new AuditLog();log.setUser(user);log.setAction(type.name());log.setEntityType("Transaction");log.setEntityId(transaction.getId());log.setDescription(transaction.getStatus().name());auditLogs.save(log);return transaction;}
private void validateAmount(BigDecimal amount){if(amount==null||amount.signum()<=0)throw new IllegalArgumentException("Amount must be greater than zero");}}
